baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Pragmatik"
theme = "terminal"
paginate = 5

[params]
  subtitle = "Cybersecurity Labs & Walkthroughs"
  contentTypeName = "posts"
  themeColor = "green"
  centerTheme = true

[[menu.main]]
  name = "Enum"
  url = "/exnumeration/"
  weight = 20

[[menu.main]]
  name = "Reverse Shells"
  url = "/reverse-shells/"
  weight = 30

[[menu.main]]
  name = "PrivEsc"
  url = "/privesc/"
  weight = 40

